# Setup
name:         Project or Site name (Architect Theme)
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "http://lfneves.github.io/BRKS/"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
